### ISSUE TITLE
The API keys are exposed

### ISSUE THREAD

**Issue by SiddiqMohammed** [r-adnan/RhythmiBrush#1]
Great project! But your Spotify API keys are exposed. Just pushing a new commit with them hidden won't remove it from the commit history but there are options to help you with that:

Option 1 — Push a new commit without it and remove the history of the exposed commits
Option 2 — Delete the project and upload it again
Option 2 — Remove/Update the API key from Spotify API dashboard

**Comment by r-adnan** [comment]
Hi, thanks for pointing that out. I actually regenerated a new Spotify key, so the one on this repository is obsolete. We are currently working on adding the new key and making it hidden.
